//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database : DbContext
    {
        public database()
            : base("name=database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<income> incomes { get; set; }
        public virtual DbSet<incomesource> incomesources { get; set; }
        public virtual DbSet<outlay> outlays { get; set; }
        public virtual DbSet<outlayitem> outlayitems { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
