//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class incomesource
    {
        public int idSource { get; set; }
        public string sourceName { get; set; }
        public string incomeComment { get; set; }

        public virtual ICollection<income> incomes { get; set; }

        public incomesource()
        {
            incomes = new List<income>();
        }

        public override string ToString()
        {
            return sourceName;
        }

    }
}
