//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class income
    {
        public int idUser { get; set; }
        public System.DateTime incomeDate { get; set; }
        public int idSource { get; set; }
        public double incomeSum { get; set; }
        public int incomeId { get; set; }
    
        public virtual user user { get; set; }
        public virtual incomesource incomesource { get; set; }
    }
}
