//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class outlay
    {
        public int userId { get; set; }
        public System.DateTime outlayDate { get; set; }
        public int itemId { get; set; }
        public double outlaySum { get; set; }
        public int outlayId { get; set; }
    
        public virtual user user { get; set; }
        public virtual outlayitem outlayitem { get; set; }
    }
}
