//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int idUser { get; set; }
        public string userName { get; set; }
        public string status { get; set; }

        public virtual ICollection<income> incomes { get; set; }
        public virtual ICollection<outlay> outlays { get; set; }

        public user()
        {
            incomes = new List<income>();
            outlays = new List<outlay>();
        }

        public override string ToString()
        {
            return userName;
        }

    }
}
